server:
  port: 9007
spring:
  application:
    name: tensquare_search
  data:
    elasticsearch:
      cluster-nodes: 192.168.21.132:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka

