spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhuerchong/tensquare-config.git
  rabbitmq:
    host: 192.168.21.132
server:
  port: 12000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh